# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c784a25734556af41a209629a9a67867c8c4b27bdbb1b1d8c1d7d00d5228bd3e295f2a7f0d5cd58670c0b7a5c71373a995303f5bd6ee3cb1eebbd547ed8f751e

test:
  secret_key_base: aad33433d3bdf3c327471ba114d69f17698c78bf13b989df04908d69e9ef439d3d301423b71cad65b1768023d37fb1e6d12da2d212a9e3e98674ca87581bf3f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
